from tkinter import *
import tkinter.font as font

window=Tk()
window.title("interface")
window.geometry("800x400")
window.configure(bg="white")
label1=Label(window,text="Rock Paper Scissors",font=font.Font(size=20),fg="gray")
label1.pack()
frame1=Frame(window,relief="ridge",bg="yellow")
frame1.pack()
label2=Label(frame1,text="Your options",fg="gray")
label2.grid(row=0,column=0)
button1=Button(frame1,text="Rock",bg="red")
button1.grid(row=1,column=1)
button2=Button(frame1,text="Paper",bg="green")
button2.grid(row=1,column=2)
button3=Button(frame1,text="Scissors",bg="blue")
button3.grid(row=1,column=3)
frame2=Frame(window,relief="ridge",bg="gray")
frame2.pack()
label3=Label(frame2,text="Score:")
label3.grid(row=0,column=0)
label4=Label(frame2,text="You selected:")
label4.grid(row=1,column=1)
label5=Label(frame2,text="Player score:")
label5.grid(row=1,column=2)
label6=Label(frame2,text="Computer selected:")
label6.grid(row=2,column=1)
label7=Label(frame2,text="Computer score:")
label7.grid(row=2,column=2)
window.mainloop()